# Based on the "arrow" theme

ARROW_SUCCESS_COLOR='240'
ARROW_FAILURE_COLOR='204'
PATH_COLOR='110'
GIT_COLOR='240'

PROMPT='$FG[$PATH_COLOR]%c %(?.$FG[$ARROW_SUCCESS_COLOR].$FG[$ARROW_FAILURE_COLOR])∙%{$reset_color%} '
RPROMPT='$FG[$GIT_COLOR]$(git_prompt_info)%{$reset_color%}'

ZSH_THEME_GIT_PROMPT_PREFIX=" "
ZSH_THEME_GIT_PROMPT_SUFFIX=""
ZSH_THEME_GIT_PROMPT_DIRTY="*"
ZSH_THEME_GIT_PROMPT_CLEAN=""
